### ISSUE TITLE
Plugin seems broken

### ISSUE THREAD

**Issue by nyanloutre** [drone-plugins/drone-rsync#14]
Hello,

When I try to use this plugin, like this : 

```
deploy:
  rsync:
    user: trehiou
    host: computer1
    source: target/
    target: /mnt/bar
    delete: false
```

Build fail when I try to launch it. This is because the syntax for the command line of rsync is false : `rsync -az -e ssh -p 22 -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o StrictHostKeyChecking=no /foo/target/ trehiou@computer1:/mnt/bar`
To set the port you should use -port=22 and not -p 22 because it's not the same option (`-p, --perms                 preserve permissions`).
