### ISSUE TITLE
Malformed section deploys entire repo

### ISSUE THREAD

**Issue by nils-werner** [drone-plugins/drone-rsync#5]
I was hoping I could use a config like

```
deploy:
  rsync:
    when:
      branch: master
    user: me
    host: server
    port: 22
    source:
      - file1.txt
      - file2.txt
    target: public_html
```

(note the list of `source` files) to deploy multiple files. However this breaks in an unexpected way: It is equal to

```
deploy:
  rsync:
    when:
      branch: master
    user: me
    host: server
    port: 22
    source:
    target: public_html
```

which deploys the entire workspace to my server :-)
